export const allergens = [
  "alcohol-free",
  "celery-free",
  "crustacean-free",
  "dairy-free",
  "egg-free",
  "fish-free",
  "fodmap-free",
  "gluten-free",
  "lupine-free",
  "mollusk-free",
  "mustard-free",
  "No-oil-added",
  "peanut-free",
  "pork-free",
  "red-meat-free",
  "sesame-free",
  "shellfish-free",
  "soy-free",
  "sulfite-free",
  "tree-nut-free",
  "wheat-free",
];

export const mealTypesArray = [
  "breakfast",
  "brunch",
  "lunch",
  "dinner",
  "snack",
];
export const dishTypeArray = [
  "alcohol cocktail",
  "biscuits and cookies",
  "bread",
  "desserts",
  "drinks",
  "egg",
  "main course",
  "pasta",
  "pastry",
  "pies and tarts",
  "pizza",
  "salad",
  "sandwiches",
  "seafood",
  "side dish",
  "soup",
  "starter",
  "sweets",
];

export const cuisineType = [
  "american",
  "asian",
  "british",
  "caribbean"
];
// export const cuisineType = [
//   "american",
//   "asian",
//   "british",
//   "caribbean",
//   "central",
//   "europe",
//   "chinese",
//   "eastern",
//   "europe",
//   "french",
//   "greek",
//   "indian",
//   "italian",
//   "japanese",
//   "korean",
//   "kosher",
//   "mediterranean",
//   "mexican",
//   "middle",
//   "eastern",
//   "nordic",
//   "south",
//   "american",
//   "south",
//   "east",
//   "asian",
// ];
